Models/Projects.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IS4439_CA2.Models
{
    public class Projects
    { 
        public int ProjectsID { get; set; }
        [Required(ErrorMessage ="Please enter a valid description")]
        [Display(Name ="Project Description")]
        [StringLength(500, MinimumLength = 10, ErrorMessage = "Please have the title within 10 and 500 characters")]

        public string ProjectDescription { get; set; }

        [Required(ErrorMessage = "Please enter a valid title")]
        [Display(Name = "Project Title")]
        [StringLength(100, MinimumLength = 5, ErrorMessage ="Please have the title within 5 and 100 characters")]
        public string ProjectTitle { get; set; }
        
        [Required(ErrorMessage = "Please enter a valid completion date")]
        [Display(Name = "Date Completed")]
        public string DateCompleted { get; set; }

        [Required(ErrorMessage = "Please enter a valid resolution")]
        [Display(Name = "Project Resolution")]
        public string Resolution { get; set; }
        [Required]
        [Display(Name = "Check if video")]

        public bool isVideo { get; set; }

        public string Dir { get; set; }
        public List<ProjectImages> ProjectImages { get; set; }

        public List<ProjectComments> ProjectCommentsID { get; set; }
    }
}

Controllers/ProjectImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IS4439_CA2.Data;
using IS4439_CA2.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using System.Text.RegularExpressions;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace IS4439_CA2.Controllers
{
    [Authorize]
    public class ProjectImagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _User;
        public ProjectImagesController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            _context = context;
            _User = user;

        }
        private async Task<ApplicationUser> GetCurrentUser()
        {
            return await _User.GetUserAsync(HttpContext.User);
        }

        // GET: ProjectImages
        public async Task<IActionResult> Index(int id)
        {
            ApplicationUser user = await GetCurrentUser();
            if(user == null || !user.IsAdmin)
            {
                return Redirect("/");
            }
            var applicationDbContext = _context.ProjectImages.Include(p => p.Project).Where(p => p.ProjectId == id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProjectImages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ApplicationUser user = await GetCurrentUser();
            if (user == null || !user.IsAdmin)
            {
                return Redirect("/");
            }

            if (id == null)
            {
                return NotFound();
            }

            var projectImages = await _context.ProjectImages
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.ProjectImagesID == id);
            if (projectImages == null)
            {
                return NotFound();
            }

            return View(projectImages);
        }

        // GET: ProjectImages/Create
        public IActionResult Create(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            ViewData["ProjectId"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFileCollection formFiles, int ProjectId)
        {
            ApplicationUser user = await GetCurrentUser();
            if (user == null || !user.IsAdmin)
            {
                return Redirect("/");
            }

            if (formFiles.Count == 0)
            {
                TempData["Error"] = "Please upload at least one image!";
                return View();
            }
            Projects project = await _context.Projects.FindAsync(ProjectId);
            string Dir = project.Dir;
            List<ProjectImages> pi = new List<ProjectImages>();
            foreach (IFormFile image in formFiles)
            {
                string imageName = ContentDispositionHeaderValue.Parse(image.ContentDisposition).FileName.Trim('"');
                string myUniqueImageName = Convert.ToString(Guid.NewGuid());
                string FileExtension = Path.GetExtension(imageName);
                string fullImageID = myUniqueImageName + FileExtension;
                
                string dir = $"wwwroot{Dir}/{fullImageID}";
                string path = $"~{Dir}/{fullImageID}";

                if (!Directory.Exists($"wwwroot{Dir}"))
                {

                    TempData["Error"] = "Unable to add image, Please try again later";
                    return View();

                }
                using (FileStream fs = System.IO.File.Create(dir))
                {
                    image.CopyTo(fs);
                    fs.Flush();
                }
                pi.Add(new ProjectImages() { imageRoute = path });
            }

            foreach(ProjectImages p in pi)
            {
                p.ProjectId = ProjectId;
                if (ModelState.IsValid)
                {
                    _context.Add(p);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(Index), new {id = ProjectId } );
        }

        public async Task<IActionResult> Delete(int? id)
        {
            ApplicationUser user = await GetCurrentUser();
            if (user == null || !user.IsAdmin)
            {
                return Redirect("/");
            }

            if (id == null)
            {
                return NotFound();
            }
           
            var projectImages = await _context.ProjectImages
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.ProjectImagesID == id);
            if (projectImages == null)
            {
                return NotFound();
            }

            return View(projectImages);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ApplicationUser user = await GetCurrentUser();
            if (user == null || !user.IsAdmin)
            {
                return Redirect("/");
            }

            var projectImages = await _context.ProjectImages.FindAsync(id);
            int projectID = projectImages.ProjectId;
            _context.ProjectImages.Remove(projectImages);
            await _context.SaveChangesAsync();
            bool isEmpty = await IsProjectEmpty(projectID);
            if (isEmpty)
            {
                return Redirect("/");
            }
            return Redirect("/");
        }

        public async Task<bool> IsProjectEmpty(int id)
        {
            var list = _context.ProjectImages.Where(p => p.ProjectId == id).ToList();

            if(!(list.Count > 0))
            {
                var project = await _context.Projects.FindAsync(id);
                _context.Projects.Remove(project);
                await _context.SaveChangesAsync();
                return true;
            }
            return false;
         
        }
    }

}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IS4439_CA2.Data;
using IS4439_CA2.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using System.Net.Http.Headers;
using System.IO;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace IS4439_CA2.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _User;
        public ProjectsController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            _context = context;
            _User = user;
        }

        private async Task<ApplicationUser> GetCurrentUser()
        {
            return await _User.GetUserAsync(HttpContext.User);
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {   
            IEnumerable<Projects> p = await _context.Projects
                .Where(p => p.isVideo == false)
                .Include(c => c.ProjectImages)
                .ToListAsync();
            return View(p);
        }

        public async Task<IActionResult> Videos()
        {
            IEnumerable<Projects> p = await _context.Projects
                .Where(p => p.isVideo == true)
                .Include(c => c.ProjectImages)
                .ToListAsync();
            return View(p);
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects
                .Include(c => c.ProjectImages)
                .Include(b => b.ProjectCommentsID).ThenInclude(c => c.ApplicationUser)
                .FirstOrDefaultAsync(m => m.ProjectsID == id);


            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

        public async Task<IActionResult> Create()
        {
            var user = await GetCurrentUser();

            if (user == null || !user.IsAdmin)
            {
                //Assigning my own status code just for completion to the end user
                TempData["Error"] = "401: You do not have the appropiate permissions to create projects!";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(IFormFileCollection formFiles,[Bind("ProjectsID, ProjectTitle, ProjectDescription, DateCompleted, Resolution, isVideo")] Projects newProject)
        {
            if (formFiles.Count == 0)
            {
                TempData["Error"] = "Please upload at least one image!";
                return View();
            }
            var user = await GetCurrentUser();

            if (user == null || !user.IsAdmin)
            {
                return RedirectToAction(nameof(Index));
            }
            string newProjectTitle = Regex.Replace(newProject.ProjectTitle, @"\s+", "");

            string dir = $"/Projects/{newProjectTitle}/";
            newProject.Dir = dir;
            if (ModelState.IsValid)
            {
                List<ProjectImages> projectImages = new List<ProjectImages>();
        
                foreach (IFormFile image in formFiles)
                {
                    
                    string imageName = ContentDispositionHeaderValue.Parse(image.ContentDisposition).FileName.Trim('"');
                    string myUniqueImageName = Convert.ToString(Guid.NewGuid());
                    string FileExtension = Path.GetExtension(imageName);
                    string fullImageID = myUniqueImageName + FileExtension;
                    Debug.WriteLine(newProjectTitle);
                    string path = $"~/Projects/{newProjectTitle}/{fullImageID}";

                    if (!Directory.Exists($"wwwroot/Projects/{newProjectTitle}"))
                    {
                        Directory.CreateDirectory($"wwwroot/Projects/{newProjectTitle}");

                    }
                    using (FileStream fs = System.IO.File.Create($"wwwroot/Projects/{newProjectTitle}/{fullImageID}"))
                    {
                        image.CopyTo(fs);
                        fs.Flush();
                    }
                    projectImages.Add(new ProjectImages() { imageRoute = path });
                    }
                newProject.ProjectImages = projectImages;
                _context.Add(newProject);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Project sucessfully created";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ApplicationUser applicationUser = await GetCurrentUser();
 
            if (applicationUser == null || !applicationUser.IsAdmin)
            {
                //Assigning my own status code just for completion to the end user
                TempData["Error"] = "401: You do not have the appropiate permissions to create projects!";
                return RedirectToAction("Details");
            }
            var projects = await _context.Projects.FindAsync(id);
            if (projects == null)
            {
                return NotFound();
            }
            return View(projects);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectsID,ProjectDescription,ProjectTitle,DateCompleted,Resolution,isVideo")] Projects projects)
        {
            if (id != projects.ProjectsID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projects);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectsExists(projects.ProjectsID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Success"] = "Project Successfully updated";
                return RedirectToAction(nameof(Index));
            }
            return View(projects);
        }

        // GET: Projects/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {

            ApplicationUser applicationUser = await GetCurrentUser();
            if (applicationUser == null || !applicationUser.IsAdmin)
            {
                //Assigning my own status code just for completion to the end user
                TempData["Error"] = "401: You do not have the appropiate permissions to create projects!";
                return RedirectToAction("Details");
            }

            if (id == null)
            {
                return NotFound();
            }

            var projects = await _context.Projects
                .FirstOrDefaultAsync(m => m.ProjectsID == id);
            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projects = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(projects);
            await _context.SaveChangesAsync();
            TempData["Success"] = "Project Successfully deleted";

            return RedirectToAction(nameof(Index));
        }

        private bool ProjectsExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectsID == id);
        }
    }
}

Views/Projects/Create.cshtml
@model IS4439_CA2.Models.Projects

<h4>Projects</h4>
<hr />
<style>
    .form-group p {
        color: black !important;
    }
</style>
<div class="row justify-content-center mt-20">
    @if (TempData["Error"] != null)
    {
        <h4 class="text-danger">@TempData["Error"]</h4>

    }
    <div class="col-md-4">

        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectDescription" class="control-label"></label>
                <input asp-for="ProjectDescription" class="form-control tm-text-gray-dark" />
                <span asp-validation-for="ProjectDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectTitle" class="control-label"></label>
                <input asp-for="ProjectTitle" class="form-control tm-text-gray-dark" />
                <span asp-validation-for="ProjectTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCompleted" class="control-label"></label>
                <input asp-for="DateCompleted" class="form-control tm-text-gray-dark"/>
                <span asp-validation-for="DateCompleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resolution" class="control-label"></label>
                <input asp-for="Resolution" class="form-control tm-text-gray-dark" />
                <span asp-validation-for="Resolution" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label" for="isVideo">
                    <input class="form-check-input" id="isVideo" asp-for="isVideo" /> @Html.DisplayNameFor(model => model.isVideo)
                </label>
            </div>
            <div class="form-group form-check">
                <label for="formFiles">Upload one or more files using this form:</label>
                <input type="file" name="formFiles" id="formFiles" multiple />
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Projects/Delete.cshtml
@model IS4439_CA2.Models.Projects

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Projects</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resolution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resolution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isVideo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isVideo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectsID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Projects/Details.cshtml
@model IS4439_CA2.Models.Projects
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="container-fluid tm-container-content tm-mt-60">
    @{
        if (TempData["Error"] != null)
        {
            <h3 class="badge-warning">@TempData["Error"]</h3>
        }
 
    }
    <div class="row mb-4">
        <h2 class="col-12 tm-text-primary">@Model.ProjectTitle</h2>
    </div>
    <div class="row tm-mb-20">
        <div class="col-xl-8 col-lg-7 col-md-6 col-sm-12">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">

                    @{
                        int i = 0;
                        String c = "";
                        foreach (var image in Model.ProjectImages)
                        {
                            if (i == 0)
                            {
                                c = "carousel-item active";
                            }
                            else
                            {
                                c = "carousel-item";
                            }
                            i++;
                            if (Model.isVideo)
                            {
                                <div class="@c">
                                    <video autoplay muted loop controls id="tm-video">
                                        <source src="@Url.Content(String.Format(image.imageRoute))" type="video/mp4">
                                    </video>
                                </div>
                            }
                            else
                            {
                                <div class="@c">
                                    <img class="d-block w-100" alt=@image.ProjectImagesID src="@Url.Content(String.Format(image.imageRoute))">
                                </div>
                            }

                        }
                    }

                </div>
                <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        <div class="col-xl-4 col-lg-5 col-md-6 col-sm-12">
            <div class="tm-bg-gray tm-video-details">
                <h2 class="tm-text-gray-dark mb-3">Project Description:</h2>

                <p class="mb-4 tm-text-gray-dark">
                    @Model.ProjectDescription
                </p>
                <div class="mr-4 mb-2">
                    <h2 class="tm-text-gray-dark mb-3">Format: </h2>
                    <p><span class="tm-text-gray-dark">JPG</span></p>
                </div>
                <br />
                <div class="mb-4">
                    <h2 class="tm-text-gray-dark mb-3">Date Published:</h2>
                    <p><span class="tm-text-gray-dark">@Model.DateCompleted</span></p>
                    <h2 class="tm-text-gray-dark mb-3">Resolution:</h2>
                    <p><span class="tm-text-gray-dark">@Model.Resolution</span></p>
                </div>
                @if (SignInManager.IsSignedIn(User))
                {
                    @if (UserManager.GetUserAsync(User).Result.IsAdmin)
                    {
                        <a asp-controller="Projects" asp-action="Edit" asp-route-id=@Model.ProjectsID> Edit Project </a>
                        <a asp-controller="ProjectImages" asp-action="Index" asp-route-id=@Model.ProjectsID> Edit Images </a>
                        <a asp-controller="Projects" asp-action="Delete" asp-route-id=@Model.ProjectsID> Delete Project </a>
                    }
                }
            </div>


        </div>
        <div class="col pb-2">
            <form asp-controller="ProjectComments" asp-action="Create" method="post">
                <div class="form-group">
                    @if (TempData["CommentError"] != null)
                    {
                        <h3>@TempData["CommentError"]</h3>
                    }



                    @if (SignInManager.IsSignedIn(User))
                    {
                        <label for="CommentText">Your Comment</label>
                        <textarea name="CommentText" id="CommentText" class="form-control" rows="3"></textarea>

                        <label for="ApplicationUserID" hidden>text</label>
                        <input id="ApplicationUserID" name="ApplicationUserID" value=@UserManager.GetUserAsync(User).Id hidden />

                    }
                    else
                    {
                        <label for="CommentText">Your Comment</label>
                        <textarea name="CommentText" id="CommentText" class="form-control" rows="3" readonly> Please Sign in to leave a comment</textarea>

                    }
                </div>
                <label for="ProjectID" hidden>ProjectId</label>
                <input name="ProjectID" id="ProjectID" value=@Model.ProjectsID hidden />
                <button type="submit" class="btn btn-default float-right">Add Comment</button>
            </form>
        </div>

    </div>
    @{
        foreach (var comment in Model.ProjectCommentsID)
        {
            <div class="row pb-2">
                <div class="comment" style="width:100%">
                    <div class="comment-text w-100">
                        <h6 class="font-medium">@comment.ApplicationUser.FullName</h6> <span class="m-b-15 d-block">@comment.CommentText </span>
                        <div class="comment-footer" style="width:100%"><p class="text-muted float-right">@comment.CommentTimeStamp</p>  </div>
                    </div>
                </div>
            </div>
        }
    }

</div>

Views/Projects/Index.cshtml
@model IEnumerable<IS4439_CA2.Models.Projects>


<div class="container-fluid tm-container-content tm-mt-60">
    @{
        if (TempData["Error"] != null)
        {
            <h3 class="badge-warning">@TempData["Error"]</h3>
        }
        if (TempData["Success"] != null)
        {
            <h3 class="badge-success">@TempData["Success"]</h3>

        }
    }
    <div class="row mb-4">
        <h2 class="col-6 tm-text-primary">
            Latest Projects
        </h2>
        <div class="col-6 d-flex justify-content-end align-items-center">
            <h5 class="tm-text-gray-dark">
                Click to view
            </h5>
        </div>
    </div>
    <div class="row tm-mb-90 tm-gallery">
        @{
            int i = 0;
            foreach (var item in Model)
            {
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-3 mb-5">
                    <figure class="effect-ming tm-video-item">

                        <img src="@Url.Content(String.Format(item.ProjectImages[0].imageRoute))" alt="Image" class="img-fluid">

                        <figcaption class="d-flex align-items-center justify-content-center">
                            <h2>@Html.DisplayFor(modelItem => item.ProjectTitle)</h2>
                            <a asp-controller="Projects" asp-action="Details" asp-route-id="@item.ProjectsID">View more</a>
                        </figcaption>
                    </figure>
                    <div class="d-flex justify-content-between tm-text-gray">
                        <span class="tm-text-gray-dark"> @Html.DisplayFor(modelItem => item.DateCompleted)</span>
                    </div>
                </div>
                i++;
            }
        }
    </div>
</div>

Views/Projects/Videos.cshtml
@model IEnumerable<IS4439_CA2.Models.Projects>


<div class="container-fluid tm-container-content tm-mt-60">
    <div class="row mb-4">
        <h2 class="col-6 tm-text-primary">
            Latest Projects
        </h2>
        <div class="col-6 d-flex justify-content-end align-items-center">
            <h5 class="tm-text-gray-dark">
                Click to view
            </h5>
        </div>
    </div>
    <div class="row tm-mb-90 tm-gallery">
        @{
            int i = 0;
            foreach (var item in Model)
            {
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-3 mb-5">
                            <figure class="effect-ming tm-video-item">

                   
                                <video autoplay muted loop controls id="tm-video">
                                    <source src="@Url.Content(String.Format(item.ProjectImages[0].imageRoute))" type="video/mp4">
                                </video>
                                <figcaption class="d-flex align-items-center justify-content-center">
                                    <h2>@Html.DisplayFor(modelItem => item.ProjectTitle)</h2>
                                    <a asp-controller="Projects" asp-action="Details" asp-route-id="@item.ProjectsID">View more</a>
                                </figcaption>
                            </figure>
                    <div class="d-flex justify-content-between tm-text-gray">
                        <span class="tm-text-gray-dark"> @Html.DisplayFor(modelItem => item.DateCompleted)</span>
                    </div>
                </div>
                i++;
            }
        }
    </div>
</div>